import type { Gallery, Photo } from '@/lib/types';

export function generateMockGalleries(): Gallery[] {
  return [
    {
      id: 'g-1',
      photographer_id: 'p-1',
      job_id: 'j-1',
      client_id: 'c-1',
      client: { id: 'c-1', photographer_id: 'p-1', first_name: 'Sarah', last_name: 'Mitchell', email: 'sarah@email.com', tags: [], created_at: '', updated_at: '' },
      job: { id: 'j-1', photographer_id: 'p-1', title: 'Sarah & James — Wedding', status: 'delivered', metadata: {}, created_at: '', updated_at: '' } as any,
      title: 'Sarah & James — Wedding',
      description: 'A beautiful autumn wedding at Brisbane Botanic Gardens',
      slug: 'sarah-james-wedding-2026',
      access_type: 'password',
      download_permissions: { allow_full_res: true, allow_web: true, allow_favorites_only: false },
      expires_at: '2026-05-14T00:00:00Z',
      status: 'delivered',
      view_count: 47,
      photo_count: 312,
      created_at: '2026-02-10T09:00:00Z',
      updated_at: '2026-02-10T09:00:00Z',
    },
    {
      id: 'g-2',
      photographer_id: 'p-1',
      job_id: 'j-2',
      client_id: 'c-2',
      client: { id: 'c-2', photographer_id: 'p-1', first_name: 'Emily', last_name: 'Chen', email: 'emily@email.com', tags: [], created_at: '', updated_at: '' },
      job: { id: 'j-2', photographer_id: 'p-1', title: 'Emily — Portraits', status: 'delivered', metadata: {}, created_at: '', updated_at: '' } as any,
      title: 'Emily — Portraits',
      slug: 'emily-portraits-2026',
      access_type: 'email',
      download_permissions: { allow_full_res: true, allow_web: true, allow_favorites_only: false },
      status: 'delivered',
      view_count: 12,
      photo_count: 45,
      created_at: '2026-02-08T14:00:00Z',
      updated_at: '2026-02-08T14:00:00Z',
    },
    {
      id: 'g-3',
      photographer_id: 'p-1',
      job_id: 'j-3',
      client_id: 'c-3',
      client: { id: 'c-3', photographer_id: 'p-1', first_name: 'Marcus', last_name: 'Thompson', email: 'marcus@email.com', tags: [], created_at: '', updated_at: '' },
      job: { id: 'j-3', photographer_id: 'p-1', title: 'Marcus — Corporate Headshots', status: 'completed', metadata: {}, created_at: '', updated_at: '' } as any,
      title: 'Marcus — Corporate Headshots',
      slug: 'marcus-headshots-2026',
      access_type: 'public',
      download_permissions: { allow_full_res: false, allow_web: true, allow_favorites_only: false },
      status: 'ready',
      view_count: 0,
      photo_count: 28,
      created_at: '2026-02-12T11:00:00Z',
      updated_at: '2026-02-12T11:00:00Z',
    },
    {
      id: 'g-4',
      photographer_id: 'p-1',
      job_id: 'j-4',
      client_id: 'c-4',
      client: { id: 'c-4', photographer_id: 'p-1', first_name: 'Lauren', last_name: 'Brooks', email: 'lauren@email.com', tags: [], created_at: '', updated_at: '' },
      job: { id: 'j-4', photographer_id: 'p-1', title: 'Lauren & David — Engagement', status: 'editing', metadata: {}, created_at: '', updated_at: '' } as any,
      title: 'Lauren & David — Engagement',
      slug: 'lauren-david-engagement-2026',
      access_type: 'password',
      download_permissions: { allow_full_res: true, allow_web: true, allow_favorites_only: true },
      status: 'processing',
      view_count: 0,
      photo_count: 86,
      created_at: '2026-02-13T16:00:00Z',
      updated_at: '2026-02-13T16:00:00Z',
    },
    {
      id: 'g-5',
      photographer_id: 'p-1',
      job_id: 'j-5',
      client_id: 'c-1',
      client: { id: 'c-1', photographer_id: 'p-1', first_name: 'Sarah', last_name: 'Mitchell', email: 'sarah@email.com', tags: [], created_at: '', updated_at: '' },
      title: 'Sarah & James — Sneak Peeks',
      slug: 'sarah-james-sneakpeeks-2026',
      access_type: 'public',
      download_permissions: { allow_full_res: false, allow_web: true, allow_favorites_only: false },
      status: 'delivered',
      view_count: 203,
      photo_count: 8,
      created_at: '2026-02-07T19:00:00Z',
      updated_at: '2026-02-07T19:00:00Z',
    },
  ];
}

export function generateMockGalleryPhotos(count: number = 24): (Photo & { preview_url?: string })[] {
  const scenes = ['ceremony', 'reception', 'portraits', 'details', 'getting-ready', 'first-dance'];
  return Array.from({ length: count }, (_, i) => ({
    id: `gp-${i}`,
    gallery_id: 'g-1',
    photographer_id: 'p-1',
    original_key: `photos/p-1/g-1/originals/IMG_${(1000 + i).toString()}.jpg`,
    edited_key: `photos/p-1/g-1/edited/IMG_${(1000 + i).toString()}.jpg`,
    filename: `IMG_${(1000 + i).toString()}.jpg`,
    file_size: 8_000_000 + Math.random() * 12_000_000,
    width: 6000,
    height: 4000,
    exif_data: {},
    scene_type: scenes[i % scenes.length],
    quality_score: 70 + Math.floor(Math.random() * 30),
    face_data: [],
    ai_edits: {},
    manual_edits: {},
    prompt_edits: [],
    status: 'delivered' as const,
    star_rating: Math.random() > 0.7 ? 5 : 0,
    is_culled: false,
    is_favorite: Math.random() > 0.8,
    is_sneak_peek: i < 3,
    sort_order: i,
    section: scenes[i % scenes.length],
    needs_review: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    // Sample photography images — different seed per photo for variety
    preview_url: `https://picsum.photos/seed/aperture${i + 100}/800/533`,
  }));
}
